variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  IMAGE: autowp/autowp-frontend
  SONAR_HOST_URL: sonarcloud.io

stages:
  - test
  - build
  - publish

lint:
  stage: test
  image: node:16-alpine
  artifacts:
    paths:
      - node_modules
  before_script:
    - npm install
  script:
    - ./node_modules/.bin/ng lint
  interruptible: true

sonar:
  stage: test
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  interruptible: true

build:
  stage: build
  image: node:16-alpine
  artifacts:
    paths:
      - dist
  script:
    - ./node_modules/.bin/ng build --prod --no-progress --base-href=/ --extra-webpack-config webpack.extra.js
  interruptible: true

publish:
  stage: publish
  image: docker
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker pull $IMAGE:latest || true
    - docker build . -t $IMAGE:latest
    - docker push $IMAGE:latest
  only:
    - master
  interruptible: true
