variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  SONAR_HOST_URL: https://sonarcloud.io

stages:
  - test
  - build
  - publish

lint:
  stage: test
  image: node:17-alpine
  artifacts:
    paths:
      - node_modules
  before_script:
    - npm install
  script:
    - ./node_modules/.bin/ng lint
  interruptible: true

sonar:
  stage: test
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  interruptible: true

build:
  stage: build
  image: node:17-alpine
  artifacts:
    paths:
      - dist
  script:
    - ./node_modules/.bin/ng build --configuration production --no-progress --base-href=/ --extra-webpack-config webpack.extra.js
  interruptible: true

publish:
  stage: publish
  image: $CI_REGISTRY/autowp/runner-base-image
  services:
    - name: docker:dind
      alias: docker
  script:
    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_IMAGE"
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build . -t "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
  interruptible: true

publish-dockerhub:
  stage: publish
  image: $CI_REGISTRY/autowp/runner-base-image
  services:
    - name: docker:dind
      alias: docker
  script:
    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_IMAGE"
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker push autowp/autowp-frontend:latest
  only:
    - master
  interruptible: true
