variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  SONAR_HOST_URL: https://sonarcloud.io

stages:
  - test
  - build
  - publish
  - publish-dockerhub

sonar:
  stage: test
  image: $CI_REGISTRY/autowp/runner-base-image
  script:
    - ./node_modules/.bin/ng lint
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  interruptible: true

build:
  stage: build
  image: $CI_REGISTRY/autowp/runner-base-image
  artifacts:
    paths:
      - dist
  script:
    - ./node_modules/.bin/ng build --configuration production --no-progress --base-href=/ --extra-webpack-config webpack.extra.js
    - npx semantic-release

publish:
  stage: publish
  image: $CI_REGISTRY/autowp/runner-base-image
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - waitforit -address=tcp://docker:2375 -timeout=30
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_IMAGE"
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build . -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

publish-dockerhub:
  stage: publish-dockerhub
  image: $CI_REGISTRY/autowp/runner-base-image
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - waitforit -address=tcp://docker:2375 -timeout=30
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_IMAGE"
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" autowp/autowp-frontend:$CI_COMMIT_TAG
    - docker push autowp/autowp-frontend:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
