{
  "branches": ["master"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/gitlab", {
      "gitlabUrl": "https://gitlab.pereslegin.ru",
      "assets": [
        {"path": "dist.tar.gz", "label": "Distribution"}
      ]
    }]
  ]
}
