sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

script:
  - sonar-scanner
  - npm install -qq
  - ./node_modules/.bin/ng build --prod --no-progress --base-href=/ng/ --extra-webpack-config webpack.extra.js
  - docker build . -t $DOCKER_REPO

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi
