sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"

script:
  - npm install -qq
  - ./node_modules/.bin/ng build --prod --no-progress --base-href=/ng/
  - docker build . -t $DOCKER_REPO

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi
