sudo: required
language: node_js
node_js:
  - "14"
cache:
  directories:
    - "node_modules"

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

install: npm install

script:
  - ./node_modules/.bin/ng lint
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true
  - ./node_modules/.bin/ng build --prod --no-progress --base-href=/ --extra-webpack-config webpack.extra.js || travis_terminate 1;
  - docker build . -t autowp/autowp-frontend || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push autowp/autowp-frontend;
    fi
