export const environment = {
  production: true,
  apiUrl: '/api/',
  sentry: {
    dsn: 'https://2903288a1e6441b88469dea7358c913a@sentry.pereslegin.ru/3',
    environment: 'production',
  },
  languages: [
    {
      code: 'en',
      hostname: 'en.wheelsage.org',
      name: 'English',
      flag: 'flag-icon flag-icon-gb',
      locale: 'en-GB',
    },
    {
      code: 'zh',
      hostname: 'zh.wheelsage.org',
      name: '中文',
      flag: 'flag-icon flag-icon-cn',
      locale: 'zh-CN',
    },
    {
      code: 'ru',
      hostname: 'www.autowp.ru',
      name: 'Русский',
      flag: 'flag-icon flag-icon-ru',
      locale: 'ru',
    },
    {
      code: 'pt-br',
      hostname: 'br.wheelsage.org',
      name: 'Português brasileiro',
      flag: 'flag-icon flag-icon-br',
      locale: 'pt-BR',
    },
    {
      code: 'fr',
      hostname: 'fr.wheelsage.org',
      name: 'Français',
      flag: 'flag-icon flag-icon-fr',
      locale: 'fr',
    },
    {
      code: 'be',
      hostname: 'be.wheelsage.org',
      name: 'Беларуская',
      flag: 'flag-icon flag-icon-by',
      locale: 'be',
    },
    {
      code: 'uk',
      hostname: 'uk.wheelsage.org',
      name: 'Українська',
      flag: 'flag-icon flag-icon-ua',
      locale: 'uk',
    },
    {
      code: 'es',
      hostname: 'es.wheelsage.org',
      name: 'Español',
      flag: 'flag-icon flag-icon-es',
      locale: 'es-ES',
    },
    {
      code: 'it',
      hostname: 'it.wheelsage.org',
      name: 'Italiano',
      flag: 'flag-icon flag-icon-it',
      locale: 'it',
    },
  ],
  keycloak: {
    url: 'https://auth.wheelsage.org/auth/',
    realm: 'autowp',
    clientId: 'frontend',
  },
  grpcHost: '',
};
